#ifndef TokenType_h
#define TokenType_h

enum TokenType {
    STRING_TOKEN,
    NUMBER_TOKEN,
    BOOLEAN_TOKEN,
    NULL_TOKEN,
    OPEN_CURLY_PARENTHESIS_TOKEN,
    CLOSE_CURLY_PARENTHESIS_TOKEN,
    OPEN_SQUARE_PARENTHESIS_TOKEN,
    CLOSE_SQUARE_PARENTHESIS_TOKEN,
    COLON_TOKEN,
    COMMA_TOKEN,
    END_OF_FILE_TOKEN
};

#endif // TokenType_h